import type { Tariff } from "@/types";

/** Моковые тарифы для вкладки «База планов» при отсутствии сервера/API */
export const MOCK_TARIFFS: Tariff[] = [
  {
    id: 1,
    name: "Домашний 100",
    description: "Интернет для дома",
    providerId: 1,
    speed: 100,
    price: 450,
    connectionPrice: 0,
    technology: "GPON",
    hasTV: true,
    tvChannels: 120,
    hasMobile: false,
    mobileMinutes: null,
    mobileGB: null,
    mobileSMS: null,
    promoPrice: null,
    promoMonths: null,
    promoText: null,
    isActive: true,
    provider: {
      id: 1,
      name: "Ростелеком",
      slug: "rostelecom",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
  {
    id: 2,
    name: "Безлимит 300",
    description: "Высокоскоростной интернет",
    providerId: 2,
    speed: 300,
    price: 699,
    connectionPrice: 500,
    technology: "PON",
    hasTV: true,
    tvChannels: 200,
    hasMobile: true,
    mobileMinutes: 300,
    mobileGB: 15,
    mobileSMS: null,
    promoPrice: 599,
    promoMonths: 6,
    promoText: "Скидка 100 р. в первые 6 месяцев",
    isActive: true,
    provider: {
      id: 2,
      name: "МТС",
      slug: "mtc",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
  {
    id: 3,
    name: "Игровой 500",
    description: "Минимальная задержка",
    providerId: 3,
    speed: 500,
    price: 899,
    connectionPrice: 0,
    technology: "GPON",
    hasTV: false,
    tvChannels: null,
    hasMobile: false,
    mobileMinutes: null,
    mobileGB: null,
    mobileSMS: null,
    promoPrice: null,
    promoMonths: null,
    promoText: null,
    isActive: true,
    provider: {
      id: 3,
      name: "Дом.ru",
      slug: "domru",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
  {
    id: 4,
    name: "Стандарт 50",
    description: "Базовый тариф",
    providerId: 1,
    speed: 50,
    price: 350,
    connectionPrice: 300,
    technology: "xDSL",
    hasTV: false,
    tvChannels: null,
    hasMobile: false,
    mobileMinutes: null,
    mobileGB: null,
    mobileSMS: null,
    promoPrice: null,
    promoMonths: null,
    promoText: null,
    isActive: true,
    provider: {
      id: 1,
      name: "Ростелеком",
      slug: "rostelecom",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
  {
    id: 5,
    name: "Семейный 200 + ТВ",
    description: "Интернет и ТВ для всей семьи",
    providerId: 2,
    speed: 200,
    price: 749,
    connectionPrice: 0,
    technology: "PON",
    hasTV: true,
    tvChannels: 150,
    hasMobile: true,
    mobileMinutes: 500,
    mobileGB: 20,
    mobileSMS: null,
    promoPrice: 649,
    promoMonths: 12,
    promoText: "Акция на год",
    isActive: true,
    provider: {
      id: 2,
      name: "МТС",
      slug: "mtc",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
  {
    id: 6,
    name: "Офис 100",
    description: "Для малого бизнеса",
    providerId: 3,
    speed: 100,
    price: 1200,
    connectionPrice: 1000,
    technology: "GPON",
    hasTV: false,
    tvChannels: null,
    hasMobile: false,
    mobileMinutes: null,
    mobileGB: null,
    mobileSMS: null,
    promoPrice: null,
    promoMonths: null,
    promoText: null,
    isActive: true,
    provider: {
      id: 3,
      name: "Дом.ru",
      slug: "domru",
      logo: "",
      description: "",
      website: "",
      phone: "",
      rating: 0,
      reviewsCount: 0,
      isActive: true,
    },
  },
];
