import type { Order } from "@/types";

/** Одна заявка-заглушка как на макете (для вёрстки без API/Docker) */
const base: Omit<Order, "id"> = {
  userId: null,
  tariffId: 1,
  providerId: 1,
  status: "new",
  firstName: "Денис",
  lastName: "Чикасов",
  fullName: "Денис Чикасов",
  phone: "+7 111 111-11-11",
  email: null,
  dateOfBirth: "11.11.1111",
  citizenship: "Российское гражданство",
  regionId: null,
  cityId: null,
  streetId: null,
  buildingId: null,
  apartmentId: null,
  addressString: null,
  entrance: null,
  floor: null,
  intercom: null,
  preferredDate: null,
  preferredTimeFrom: null,
  preferredTimeTo: null,
  routerOption: null,
  routerNeed: null,
  routerPurchase: null,
  routerOperator: null,
  routerConfig: null,
  routerPrice: null,
  tvSettopOption: null,
  tvSettopPrice: null,
  simCardOption: null,
  simCardPrice: null,
  totalMonthlyPrice: null,
  totalConnectionPrice: null,
  totalEquipmentPrice: null,
  assignedTo: null,
  internalComment: null,
  comment: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  tariff: { id: 1, name: "—", description: "", providerId: 1, speed: 0, price: 0, connectionPrice: 0, technology: "", hasTV: false, tvChannels: null, hasMobile: false, mobileMinutes: null, mobileGB: null, mobileSMS: null, promoPrice: null, promoMonths: null, promoText: null, isActive: true },
  provider: { id: 1, name: "MTC", slug: "mtc", logo: "", description: "", website: "", phone: "", rating: 0, reviewsCount: 0, isActive: true },
};

/** Фиктивные адреса заявок (для вкладки «База адресов» при отсутствии API) */
const MOCK_ADDRESS_STRINGS: string[] = [
  "гор. Москва, наб. Кремлевская, д. 9 к 6",
  "гор. Москва, Варшавское шоссе, 125",
  "Санкт-Петербург, Невский проспект, 28",
  "гор. Москва, ул. Тверская, 12",
  "Казань, ул. Баумана, 58",
  "Новосибирск, Красный проспект, 77",
  "Екатеринбург, ул. Ленина, 52",
  "гор. Москва, Ленинградское шоссе, 39",
  "Нижний Новгород, ул. Большая Покровская, 1",
  "Самара, ул. Куйбышева, 100",
];

/** 10 заявок-заглушек с разными адресами (для вкладок «Все» и «База адресов» без API) */
export const MOCK_ORDERS: Order[] = Array.from({ length: 10 }, (_, i) => ({
  ...base,
  id: 10 - i,
  addressString: MOCK_ADDRESS_STRINGS[i % MOCK_ADDRESS_STRINGS.length],
  connectionType: i % 3 === 0 ? "private" : i % 3 === 1 ? "office" : "apartment",
}));
